### ISSUE TITLE
Examples from exercise 2 and 3 are not running in development mode

### ISSUE THREAD

**Issue by mjbertenburg** [kentcdodds/react-performance#1]
Hey,
I discovered that the code from neither exercise`02.extra-2.js` nor `03.js` is running properly when serving it in development mode locally. Instead an error is logged to the console:

```
react-dom.development.js:22839 Uncaught 
TypeError: (0 , _workerized_filter_cities__WEBPACK_IMPORTED_MODULE_2__.getItems) is not a function
    at 03.js:69:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at react-dom.development.js:26769:1
    at workLoop (scheduler.development.js:266:1)
```

By contrast, it does work when building the code in production mode.

**Comment by kentcdodds** [comment]
Yeah, I've noted this in the instructions (I thought it already was). Workerized sometimes has issues and it's unclear to me what causes those issues. I don't necessarily recommend Workerized (it was just an easy way to add web workers to a project). In Epic React v2, we're using Vite and there's a built-in mechanism for web workers (see [that exercise here](https://react-performance.epicweb.dev/05/02/problem)). But even there, the specific mechanism for web workers matters much less than the use of web workers which is the objective of the lesson.
